export enum SseEvents {
  ACTUAL_SONG_SPTF = 'ACTUAL_SONG_SPTF',
  ACTUAL_VOTES_SPTF = 'ACTUAL_VOTES_SPTF',
  NEW_WINNER_SPTF = 'NEW_WINNER_SPTF',
  YOU_WIN_SONG_VOTE_SPTF = 'YOU_WIN_SONG_VOTE_SPTF',
  UPDATE_COINS = "UPDATE_COINS",
  NEW_PRIZE = "NEW_PRIZE",
  LOGOUT_SPOTIFY = "LOGOUT_SPOTIFY",
}